name: Tracking the issue
on:
  issues:
    types: [opened]

permissions:
  issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - run: echo "${{ secrets.FLAG2 }}" > flag.txt
      - uses: hackerify/issue-template@main
